datasource:
  driver-class-name: 'org.postgresql.Driver'
  schema: 'dfejis77nibjdr'
  url: 'jdbc:postgresql://ec2-52-214-125-106.eu-west-1.compute.amazonaws.com:5432/dfejis77nibjdr'
  username: 'qexdvxvgdqtdgh'
  password: 'bf7f8df51b60c17d1fcc333c3f7b63e57df7300022deb67d60eb6cee2bd4e5dd'

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring:
  datasource:
    name: 'StoragePostgreSQL'
    driverClassName: '${datasource.driver-class-name}'
    url: '${datasource.url}'
    username: '${datasource.username}'
    password: '${datasource.password}'

  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'
    enabled: false
    url: '${datasource.url}'
    user: '${datasource.username}'
    password: '${datasource.password}'
    parameters:
      env: '${spring.profiles.active}'

  security:
    user:
      name: yb3129h@gre.ac.uk
      password: 19973858@7837~43b2!bd7a%2f4504f2ea0e